# Site settings
title: PostDeploy
title1: Post
title2: Deploy
email: info@postdeploy.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8FA7CF #5776A7 #18bc9c #80B3FF
  secondary: 777 #064D41 #2c3e50 #FD6E8A
  secondary-dark: 00E6C6 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/postdeploy
  - title: github
    url: http://github.com/postdeploy

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty

# Google Analytics
google_analytics: UA-54765968-1
